defaults:
  -
    # All YANIs (i.e. all posts) share these default values.
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      category: ["vanilla"]
      implementors: []

collections:
  yanis:
    output: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
