title: NetHack Ideas Archive
email: aosdict@gmail.com
description: >-
  This is a collection of ideas, suggestions, and feature requests for the game
  NetHack, preserving good ideas so they don't get forgotten about and
  presenting them in an organized format for use by developers.

defaults:
  -
    # All YANIs (i.e. all posts) share these default values.
    scope:
      path: ""
    values:
      layout: "default"

# Set up YANIs as a collection so the files can be in _yanis/ and named 1.md,
# 2.md, etc instead of having to have them in _posts/ and given date-based
# filenames.
collections:
  yanis:
    output: true
  bigideas:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
